# Generated by Django 3.2.13 on 2022-11-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('metropolitan_city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
        ),
    ]
